version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "23:00"
    timezone: PST8PDT
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ajv-formats
    versions:
    - 2.0.2
  - dependency-name: postcss
    versions:
    - 8.2.6
    - 8.2.8
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.3
  - dependency-name: react-resize-detector
    versions:
    - 6.3.1
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "23:00"
    timezone: PST8PDT
  open-pull-requests-limit: 10
